//
// Created by Dan Jiang on 2020/8/19.
//

#ifndef LEARN_CPP_WITH_CPP_PRIMER__CH10_GENERIC_ALGORITHMS_H_
#define LEARN_CPP_WITH_CPP_PRIMER__CH10_GENERIC_ALGORITHMS_H_

void exercise_10_1();

#endif //LEARN_CPP_WITH_CPP_PRIMER__CH10_GENERIC_ALGORITHMS_H_
