//
// Created by Dan Jiang on 2020/9/1.
//

#ifndef LEARN_CPP_WITH_CPP_PRIMER__CH12_DYNAMIC_MEMORY_AND_SMART_POINTERS_H_
#define LEARN_CPP_WITH_CPP_PRIMER__CH12_DYNAMIC_MEMORY_AND_SMART_POINTERS_H_

void exercise_12_1();
void exercise_12_2();

#endif //LEARN_CPP_WITH_CPP_PRIMER__CH12_DYNAMIC_MEMORY_AND_SMART_POINTERS_H_
