//
// Created by Dan Jiang on 2020/10/31.
//

#ifndef LEARN_CPP_WITH_CPP_PRIMER__CH16_TEMPLATES_AND_GENERIC_PROGRAMMING_H_
#define LEARN_CPP_WITH_CPP_PRIMER__CH16_TEMPLATES_AND_GENERIC_PROGRAMMING_H_

void exercise_16_1();

#endif //LEARN_CPP_WITH_CPP_PRIMER__CH16_TEMPLATES_AND_GENERIC_PROGRAMMING_H_
