//
// Created by Dan Jiang on 2020/4/11.
//

#ifndef LEARN_CPP_WITH_CPP_PRIMER__CH2_VARIABLES_AND_BASIC_TYPES_H_
#define LEARN_CPP_WITH_CPP_PRIMER__CH2_VARIABLES_AND_BASIC_TYPES_H_

void exercise_2_3();

#endif //LEARN_CPP_WITH_CPP_PRIMER__CH2_VARIABLES_AND_BASIC_TYPES_H_
